module.exports={
    PRODUCT_COLLECTION:'product',
    USER_COLLECTION:'user',
    PRODUCT_CATEGORY:'category',
    CART_COLLECTION:'cart',
    ORDER_COLLECTION:'order',
    WISHLIST_COLLECTION:'wishlist',
    PROFILE_COLLECTION:'profile',
    CAROUSEL_COLLECTION:'carousel',
    ORDERD_ADDRESS:"address",
    COUPEN_COLLECTION:"coupen"
}